# Generated by Django 4.1 on 2024-06-18 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_match_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_post_title', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('employment_type', models.CharField(choices=[('Tillsvidareanställning', 'Tillsvidareanställning'), ('Provanställning', 'Provanställning'), ('Deltid', 'Deltid')], max_length=22)),
                ('job_description', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=20)),
                ('expiration_date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekerCv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=30)),
                ('applied_profiles', models.ManyToManyField(related_name='applicants', to='job_match_backend_app.jobpost')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_ag',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WorkExperince',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_title', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=50)),
                ('years', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='job_match_backend_app.jobseekercv')),
            ],
        ),
        migrations.AddField(
            model_name='jobseekercv',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('orientation', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='job_match_backend_app.jobseekercv')),
            ],
        ),
    ]
