# Generated by Django 4.1 on 2024-06-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_match_backend_app', '0003_alter_jobpost_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
