# Generated by Django 4.1 on 2024-06-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_match_backend_app', '0004_jobpost_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='years',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
