# Generated by Django 4.1 on 2024-06-30 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("job_match_backend_app", "0006_application"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="applications",
            field=models.ManyToManyField(
                related_name="job_applications",
                through="job_match_backend_app.Application",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="job_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_applications",
                to="job_match_backend_app.jobpost",
            ),
        ),
    ]
