# Generated by Django 4.1 on 2024-06-30 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "job_match_backend_app",
            "0007_jobpost_applications_alter_application_applicant_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="job_seeker_cv",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="job_match_backend_app.jobseekercv",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="job_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
