# Generated by Django 4.1 on 2024-06-30 20:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "job_match_backend_app",
            "0008_application_job_seeker_cv_alter_jobpost_job_post",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="applicant",
            new_name="profile_id",
        ),
    ]
