# Generated by Django 4.1 on 2024-07-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_match_backend_app', '0010_alter_education_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperince',
            name='years',
            field=models.CharField(max_length=10),
        ),
    ]
